# PupsAndPlaygrounds Pods
target 'PupsAndPlaygrounds' do
  use_frameworks!

  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'

  # Facebook
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  # Google Maps
  pod 'GoogleMaps'
#  pod 'GooglePlaces'

  # XML Parser
  pod 'SWXMLHash'

  # SnapKit
  pod 'SnapKit', '~> 3.0'


end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
