# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'GeoFireTest' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GeoFireTest
  pod 'Firebase'
  pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git’


end
